### ISSUE TITLE
X1Plus startup failed.

### ISSUE THREAD

**Issue by nullvoid413** [X1Plus/X1Plus#114]
**Describe the bug**
When booting with SD card, appears the message "X1Plus startup failed. Initramfs shell is available on UART at 1500000 baud."

**To Reproduce**
1. Just installed following the guide.

**Screenshots/Photos**
![image](https://github.com/X1Plus/X1Plus/assets/18699811/55424c51-f5a3-4511-9a34-70d8e702c2db)

**Comment by nullvoid413** [comment]
Formatted SD card through printer and reinstalled fw. Worked fine.

/Closed.

**Comment by qhga** [comment]
Leaving this for others that might have a similar problem: For me, this error even persisted after two formats (via printer and `mkfs.vfat -F32`). Turns out, it was a slighly faulty SD card. Switched the SD card and everything worked as expected.
