### ISSUE TITLE
remove nfs / nfsd from kernel

### ISSUE THREAD

**Issue by bani6809** [X1Plus/X1Plus#117]
i can't see us seriously supporting nfs client let alone nfs server, we should remove and get kernel memory back.

**Comment by nelsmar** [comment]
If enough peopole want this I can look into. I personally have a use for this and others may. But making a toggle or a different kernel for "effiecency" might be ideal. Can you explain more in detail what and why you are seeing use in this and how the memory issues are holding you back from something so I can further understand?

**Comment by jwise** [comment]
yeah, -1; I don't think that the cost of nfsd is even perceptible on this printer.  I took a guess at '200 KB' and then decided to actually look it up, and dang was I close:

```
joshua@anima:kernel-x1plus$ size `find fs/nfs fs/nfsd fs/nfs_common -iname '*.o'` -t | tail -n1
 189505	  1611	  1828	192944	 2f1b0	(TOTALS)
```

(that's text, data, bss, total decimal, total hex)

**Comment by jwise** [comment]
closing wnf
