### ISSUE TITLE
translation does not work correctly on FW < 01.07.02.00

### ISSUE THREAD

**Issue by jwise** [X1Plus/X1Plus#146]
kexec_ui crashes on 01.07.00.00 now.

We should probably just detect bblap version and refuse to do the language injection thing in kexec_ui on any version older than FW R / the officially supported bblap version.  It is pretty brittle and we can't really maintain it for all of bbl_screen history, I suppose.  Maybe we could get BBL to add a hook for us for this...

**Comment by balika011** [comment]
I would argue that there is no real benefit in fixing this as kexec_ui runs on fw r anyways.

**Comment by jwise** [comment]
I sort of agree but also there is an extremely tiny minority of legacy users who are still in the non-R world and it would be good not to break them.

**Comment by riptidewave93** [comment]
Do we want to work with said older base FW users to move them up to Firmware R? My only concern is devices that are not compatible (early kickstarter printers). @jwise did we bring that issue up to Bambu?

**Comment by jwise** [comment]
I don't know of any early KS printers that are not compatible with FW R.  Do you know of any?  I know of one and only one AP board that is not compatible, and that was a preproduction unit.
