### ISSUE TITLE
In order to enable IDEX functionality - Allow X1C to print on top of an add on item placed on the bed, plus allow Z axis and pausing to be synchronised between multiple X1Cs

### ISSUE THREAD

**Issue by ukdavewood** [X1Plus/X1Plus#182]
**Is your feature request related to a problem? Please describe.**
I would like to explore the concept of adding some sort of moving bed add on to the top of the X1C print bed - to allow a) Part ejection, b) Bigger models on a single printer, and c) IDEX like collaboration between two printers.
See this video for an illustration of the concept https://youtu.be/uXqAenyT-fY

**Describe the solution you'd like**
a) Allowing the Z axis probing to cope with a large item place on the print bed.
       Which as the add on proposed in this video.  
b) Allow the Z axis height between two printers to be coordinated - perhaps via something external like Octoprint - so that an add on bed could span two printers - for idex like printing.     I don't think parallel printing will be practical - so only one printer would be able to print at a time - but it might be possible to do low quality things that are not too Z height dependent - like prime tower printing in parallel.

**Describe alternatives you've considered**
Just a concept at this stage.  I haven't done a lot of testing to see what is needed to convince a printer to print on top of an existing item.   Also haven't investigated what is already possible with MQTT / Home assistant for example.

**Software Information**
 - Current X1Plus Version:  Haven't yet tried installing X1Plus

**Additional context**
Add any other context or additional information about the feature request here.

**Comment by RobinWhitfield** [comment]
I'm marking this as something that will not be worked on, as although it's a very cool idea, the hardware side of things (how you'd handle bed mesh, how you'd connect the belt to the printer) would want to be at least prototyped before anything was considered in terms of X1Plus.

At this point, this idea would be best off as either a discussion in ideally the Discord server (https://discord.gg/4SfCufp6SB) or here on Github (https://github.com/X1Plus/X1Plus/discussions).
Once some idea of the feasibility and plan for the hardware had been established, then the requirements for the software could be discussed, and then logged as specific feature requests as required.
