### ISSUE TITLE
How to update firmware V1 to 1.1

### ISSUE THREAD

**Issue by woolmonkey** [X1Plus/X1Plus#192]
I tried the new installer 1.1 on and already custom firmwared machine and it says copy the x1p file to the sdcard and reboot.  I did that but it's still running the old firmware.  There was 1.0.x1p and I copied cfw.x1p over.

**Comment by jphannifan** [comment]
> I tried the new installer 1.1 on and already custom firmwared machine and it says copy the x1p file to the sdcard and reboot. I did that but it's still running the old firmware. There was 1.0.x1p and I copied cfw.x1p over.

Refer to this section of the Wiki. https://github.com/X1Plus/X1Plus/wiki/User-Manual#bootloader-menu

I will edit the headings of the wiki so this is more clear. In an upcoming version of X1Plus, you will be able to download updates from the device, so it will be much simpler in the near future.
