### ISSUE TITLE
1.1 wifi drivers do not support DE region channels

### ISSUE THREAD

**Issue by bani6809** [X1Plus/X1Plus#197]
it appears the 1.1 wifi drivers do not support wifi channels 12,13 (DE)

likely missing from the murata regulatory clm.

this is probably the cause of issues #184 and other reports on the discord server.

**Comment by jwise** [comment]
Remind me how we decided it is the firmware and not brcmfmac?

**Comment by bani6809** [comment]
> Remind me how we decided it is the firmware and not brcmfmac?

as much as I would have liked to blame brcmfmac, i was systematic and ruled it out by having Digilol on discord repro their bug with these builds: https://github.com/X1Plus/X1Plus/releases/tag/v1.0-7-brcmfmac

one is murata, one is murata+brcmfmac

bug repro'd in both. and in both cases user resolved their problem by changing from channel 13 to another channel.

**Comment by bani6809** [comment]
should be fixed by 0f906c3e4b7e9af948d2bcc5132666a3a23426fe
