### ISSUE TITLE
i can't install x1 plus at all

### ISSUE THREAD

**Issue by boomer20021** [X1Plus/X1Plus#233]
**Describe the bug**

**To Reproduce**
1. Print '...'
2. Wait for '....'
3. Tap on '....'

**Expected behavior**

**Screenshots/Photos**
If applicable, add screenshots or photos to help explain your problem.

**External Links**
Has this bug been discussed elsewhere that you can link to? Have you checked this repository's discussions section?

**Additional Details:**
 - Printer type (X1/X1C/X1E):
 - X1Plus version:
 - AP firmware version:
 - AP hardware revision:
 - MC firmware version:
 - MC hardware revision:
 - Toolhead firmware version:
 - Toolhead hardware revision:
 - Computer vision model:

**Is the bug present on OEM firmware?**
Have you tested whether this bug is also present in OEM firmware?
If it is, which version? *ex. 01.07.02.00*
Are any steps to replicate it different?

**Custom modifications**
Add details of any software or electronic modifications you've made to your printer here.

**Additional context**

**Comment by jwise** [comment]
This is not a bug report.
