### ISSUE TITLE
Better control of toolhead LED

### ISSUE THREAD

**Issue by LJKraus** [X1Plus/X1Plus#241]
I prefer to keep the useless tool head LED off, so I was glad to see that X1+ gave me some control of the light.

But...

The light comes back on when a print begins and it stays on when the print is over.  The onscreen control has to be switched to On before it can be turned back Off.

I'm not calling this a bug because I don't know if it is even possible to keep the light off, or turn it off after print completion, but one of these options would be nice.

**Comment by reipet** [comment]
You can add this Gcode into your Slicers Filament Setting under advanced:
M960 S5 P0

Can switch of the Light before or once the print is completed. Works fine at the print end for me.
