### ISSUE TITLE
reports of x1plus-settings having weird defaults

### ISSUE THREAD

**Issue by jwise** [X1Plus/X1Plus#253]
I need to, like, blast the SD card on my printer and start fresh or something and see if I can reproduce this.

**Comment by jphannifan** [comment]
Weird behavior I've been noticing lately. My printer is running the same x1p as the artifact build from PR 260 (kexec stuff)

Regardless of the setting I have for `homescreen.graph.enabled` the graph is displaying no matter what. 
<img width="350" alt="image" src="https://github.com/X1Plus/X1Plus/assets/149451641/e60e0e8d-1c57-4358-a6fd-82c64399be5d">

I had no `homescreen.image.printing` defined and `homescreen.graph.enabled` true/false (same result either way)

I just set `homescreen.image.printing` to a .png on my SD card and now the lines appear on the plot but no background image.

**Comment by jphannifan** [comment]
Update, this appears to be related to `x1plus-test-settings.py` saving everything as a string. 

When settings.json looks like this, the graph is enabled no matter what:
```
"homescreen.graph.enabled": "false"
```

However change it to this and the issue is gone:
```
"homescreen.graph.enabled": false
```

**Comment by jwise** [comment]
Yeah, that's correct.  `x1plus-test-settings.py` is very much not industrial-strength right now.  On the command line if you wish to delete a key, try `x1plus-test-settings.py homescreen.graph.enabled=None`.  Once the OTA stuff is a little more stable and there are more interesting X1Plus endpoints to hit, `x1plus-test-settings.py` will become a more full-fat CLI tool.

**Comment by jphannifan** [comment]
> Yeah, that's correct. `x1plus-test-settings.py` is very much not industrial-strength right now. On the command line if you wish to delete a key, try `x1plus-test-settings.py homescreen.graph.enabled=None`. Once the OTA stuff is a little more stable and there are more interesting X1Plus endpoints to hit, `x1plus-test-settings.py` will become a more full-fat CLI tool.

The only issue I'm still having is I'm unable to view the plots when a print is running. See the image above, that's what it looks like if I print with `homescreen.graph.enabled` set to True. It does display everything correctly while the printer is idle, so I have a feeling it's something weird with Home2Page.qml

**Comment by jphannifan** [comment]
@jwise I think this issue is fixed now. Any recent reports before we close this?

**Comment by jwise** [comment]
I also think this is fixed now, with the new `x1plus settings` tool that ought be quite a bit more bulletproof.
