### ISSUE TITLE
option to use oem wifi drivers

### ISSUE THREAD

**Issue by bani6809** [X1Plus/X1Plus#278]
there are still users reporting issues with x1plus wifi drivers. specifically @hobbybob -> https://discord.com/channels/1041781310299062282/1233015570610524160

add a ui switch somewhere to enable the option to use the oem wifi drivers. likely requires a reboot.

**Comment by bani6809** [comment]
will likely require a dual kernel setup. oem fw does not like brcmfmac and bcmdhd module won't load in x1plus kernel due to missing symbols.

**Comment by jphannifan** [comment]
done
