### ISSUE TITLE
Been able to perform print screen

### ISSUE THREAD

**Issue by Alkerion** [X1Plus/X1Plus#321]
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. "Change menu item to be z instead"
Add a button, or map physical button to perform a print screen.

I'd love to make screenshot of screens, especially bed mesh and vibration calibration results.

**Software Information**
 - Current X1Plus Version: 2.0rc

**Comment by psiberfunk** [comment]
You can do this already with a VNC connection from a computer ?

**Comment by Alkerion** [comment]
Ok, thanks.

I've been able to setup VNC and perform a print screen.
