### ISSUE TITLE
Version 2.0 has no ABS-GF

### ISSUE THREAD

**Issue by Shadow27374** [X1Plus/X1Plus#342]
Hello,

I have a roll of ABS-GF from Bambu Lab outside the AMS in the so-called external spool. Therefore I have to select the filament type manually via the display.

Unfortunately there is no ABS-GF there. Of course I can set it via Bambu Studio but the printer always rejects it and forgets its external spool.

I have just updated from X1Plus 1.1 to 2.0. The version is also displayed correctly in the menu. MC Board then wanted an update, which was also carried out.
Unfortunately, ABS-GF is still missing.

**Comment by jphannifan** [comment]
We are working on a solution for this in https://github.com/X1Plus/X1Plus/issues/354

We have a manual fix for those who have this issue, and feel free to contact me if you need help
