### ISSUE TITLE
[Feature Request] - Include newer WiFi drivers.

### ISSUE THREAD

**Issue by RobinWhitfield** [X1Plus/X1Plus#55]
**Is your feature request related to a problem? Please describe.**
X1 WiFi still kinda sucks, maybe new drivers will fix it.

**Describe the solution you'd like**
Add new drivers to X1Plus, test, be happy.

**Describe alternatives you've considered**
Continue to be on our of date drivers and potentially be missing out on improvements

**Software Information**
 - X1Plus Version: <=1.0

**Comment by jwise** [comment]
fixed by #84, #85
