### ISSUE TITLE
Incorrect Linux installer file extension

### ISSUE THREAD

**Issue by shyblower** [X1Plus/X1Plus#88]
**Describe the bug**
The Linux installer file extension on the release page incorrectly is ".zip" while the file actually is a gzipped tar and thus the extension should be ".tar.gz" or ".tgz".

**Additional Details:**
 - X1Plus version: 1.0

**Comment by campmeharder** [comment]
Thanks for reporting was going to report it.

**Comment by jwise** [comment]
Haha I tried renaming it and GitHub really wants to keep the .zip extension, so now it’s the deeply embarrassing tar.gz.zip. I’ll reupload it when I get home.

**Comment by jwise** [comment]
I have fixed it.  Sorry about that!
