### ISSUE TITLE
Add the ability to PID tuning your hotend and bed 

### ISSUE THREAD

**Issue by juancv** [X1Plus/X1Plus#89]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. "Menu item *x* is confusing and always makes me do *y* by accident"

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. "Change menu item to be z instead"

**Describe alternatives you've considered**

**Software Information**
 - Current X1Plus Version:

**Additional context**
Add any other context or additional information about the feature request here.

**Comment by jwise** [comment]
closed notabug; bug fields are not filled out, and there is no evidence provided that this is useful in any way on this printer hw
